### ISSUE TITLE
Npm packaging tests are not robust

### ISSUE THREAD

**Issue by cyberixae** [SC5/sc5-styleguide#520]
These npm packaging tests fail sometimes on my laptop and sometimes they pass. Perhaps it is a timing problem?

  3 failing

  1) style guide generated with npm package executable from SCSS test project index.html "before all" hook:
     Error: ENOENT, no such file or directory '/var/folders/cn/g75892ss5gdc_938bbm8xlf80000gn/T/sc5-package-smoketest1426772518580/scss-test-output/index.html'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at getFile (/Users/toniruottusc5/styleguide/sc5-styleguide/test/integration/npm-package.test.js:198:19)
    at Context.<anonymous> (/Users/toniruottusc5/styleguide/sc5-styleguide/test/integration/npm-package.test.js:192:21)
    at callFn (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:266:21)
    at Hook.Runnable.run (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:259:7)
    at next (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:268:10)
    at Object._onImmediate (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:289:5)
    at processImmediate [as _immediateCallback] (timers.js:345:15)

  2) style guide generated with npm package executable from LESS test project index.html "before all" hook:
     Error: ENOENT, no such file or directory '/var/folders/cn/g75892ss5gdc_938bbm8xlf80000gn/T/sc5-package-smoketest1426772518580/less-test-output/index.html'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at getFile (/Users/toniruottusc5/styleguide/sc5-styleguide/test/integration/npm-package.test.js:198:19)
    at Context.<anonymous> (/Users/toniruottusc5/styleguide/sc5-styleguide/test/integration/npm-package.test.js:192:21)
    at callFn (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:266:21)
    at Hook.Runnable.run (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:259:7)
    at next (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:268:10)
    at Object._onImmediate (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:289:5)
    at processImmediate [as _immediateCallback] (timers.js:345:15)

  3) style guide generated with npm package executable from internal client files index.html "before all" hook:
     Error: ENOENT, no such file or directory '/var/folders/cn/g75892ss5gdc_938bbm8xlf80000gn/T/sc5-package-smoketest1426772518580/demo-test-output/index.html'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at getFile (/Users/toniruottusc5/styleguide/sc5-styleguide/test/integration/npm-package.test.js:198:19)
    at Context.<anonymous> (/Users/toniruottusc5/styleguide/sc5-styleguide/test/integration/npm-package.test.js:192:21)
    at callFn (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:266:21)
    at Hook.Runnable.run (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:259:7)
    at next (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:268:10)
    at Object._onImmediate (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:289:5)
    at processImmediate [as _immediateCallback] (timers.js:345:15)

[15:42:26] 'test:integration' errored after 28 s
[15:42:26] Error in plugin 'gulp-mocha'
Message:
    3 tests failed.
[15:42:26] 'test' errored after 33 s
[15:42:26] Error: [object Object]
  at formatError (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp/bin/gulp.js:169:10)
  at Gulp.<anonymous> (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp/bin/gulp.js:195:15)
  at Gulp.emit (events.js:117:20)
  at Gulp.Orchestrator._emitTaskDone (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
  at /Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp/node_modules/orchestrator/index.js:275:23
  at finish (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at cb (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at finish (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/run-sequence/index.js:48:5)
  at Gulp.onError (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/run-sequence/index.js:55:4)
  at Gulp.emit (events.js:117:20)
  at Gulp.Orchestrator._emitTaskDone (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
  at /Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp/node_modules/orchestrator/index.js:275:23
  at finish (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at Stream.<anonymous> (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4)
  at Stream.f (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
  at Stream.emit (events.js:117:20)
  at /Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/index.js:49:14
  at done (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/mocha.js:424:20)
  at Runner.<anonymous> (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:626:5)
  at Runner.emit (events.js:117:20)
  at /Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:616:12
  at /Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:545:7
  at next (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:257:23)
  at Object._onImmediate (/Users/toniruottusc5/styleguide/sc5-styleguide/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:289:5)
  at processImmediate [as _immediateCallback] (timers.js:345:15)

npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

**Comment by cyberixae** [comment]
Others have not been able to reproduce this and I am not sure if I have it anymore myself. I'll close it for now and consider reopening it later if I encounter the bug again.
