### ISSUE TITLE
Integration tests are broken

### ISSUE THREAD

**Issue by varya** [SC5/sc5-styleguide#760]
```
  65 passing (58s)
  4 failing

  1) style guide generated with npm package executable from SCSS test project "before all" hook:
     Command exited with non-zero: 1
bin/styleguide --styleSource /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/shared-css/*.css --title Test Styleguide --overviewPath /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/test_overview.md --appRoot /my-styleguide-book --extraHead <link rel="stylesheet" type="text/css" href="your/custom/style.css"> --extraHead <script src="your/custom/script.js"></script> --commonClass custom-class-1 --commonClass custom-class-2 --styleVariables /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/styles/_styleguide_variables.scss --customColors /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/styles/custom_colors.scss --kssSource /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/**/*.scss --output /var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/scss-test-output

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: undefined is not a function
    at Function.pleeease.process (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/pleeease/lib/pleeease.js:192:11)
    at DestroyableTransform._transform (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/index.js:32:29)
    at DestroyableTransform.Transform._read (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)

  Error: Command exited with non-zero: 1
  bin/styleguide --styleSource test/projects/shared-css/*.css --title Test Styleguide --overviewPath /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/test_overview.md --appRoot /my-styleguide-book --extraHead <link rel="stylesheet" type="text/css" href="your/custom/style.css"> --extraHead <script src="your/custom/script.js"></script> --commonClass custom-class-1 --commonClass custom-class-2 --styleVariables /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/styles/_styleguide_variables.scss --customColors /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/styles/custom_colors.scss --kssSource /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/**/*.scss --output /var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/scss-test-output
  events.js:85
        throw er; // Unhandled 'error' event
              ^
  Error: undefined is not a function
      at ChildProcess.<anonymous> (test/integration/npm-package.test.js:192:16)
      at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
  From previous event:
      at Context.<anonymous> (test/integration/npm-package.test.js:41:64)

  2) style guide generated with npm package executable from LESS test project "before all" hook:
     Command exited with non-zero: 1
bin/styleguide --styleSource /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/shared-css/*.css --title Test Styleguide --overviewPath /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/test_overview.md --appRoot /my-styleguide-book --extraHead <link rel="stylesheet" type="text/css" href="your/custom/style.css"> --extraHead <script src="your/custom/script.js"></script> --commonClass custom-class-1 --commonClass custom-class-2 --styleVariables /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/less-project/source/styles/_styleguide_variables.less --customColors /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/styles/custom_colors.scss --kssSource /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/less-project/source/**/*.less --output /var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/less-test-output

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: undefined is not a function
    at Function.pleeease.process (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/pleeease/lib/pleeease.js:192:11)
    at DestroyableTransform._transform (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/index.js:32:29)
    at DestroyableTransform.Transform._read (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)

  Error: Command exited with non-zero: 1
  bin/styleguide --styleSource test/projects/shared-css/*.css --title Test Styleguide --overviewPath /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/test_overview.md --appRoot /my-styleguide-book --extraHead <link rel="stylesheet" type="text/css" href="your/custom/style.css"> --extraHead <script src="your/custom/script.js"></script> --commonClass custom-class-1 --commonClass custom-class-2 --styleVariables /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/less-project/source/styles/_styleguide_variables.less --customColors /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/styles/custom_colors.scss --kssSource /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/less-project/source/**/*.less --output /var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/less-test-output
  events.js:85
        throw er; // Unhandled 'error' event
              ^
  Error: undefined is not a function
      at ChildProcess.<anonymous> (test/integration/npm-package.test.js:192:16)
      at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
  From previous event:
      at Context.<anonymous> (test/integration/npm-package.test.js:54:64)

  3) style guide generated with npm package executable from plain CSS test project "before all" hook:
     Command exited with non-zero: 1
bin/styleguide --styleSource /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/shared-css/*.css --title Test Styleguide --overviewPath /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/test_overview.md --appRoot /my-styleguide-book --extraHead <link rel="stylesheet" type="text/css" href="your/custom/style.css"> --extraHead <script src="your/custom/script.js"></script> --commonClass custom-class-1 --commonClass custom-class-2 --styleVariables /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/styles/_styleguide_variables.scss --customColors /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/styles/custom_colors.scss --kssSource /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/css-project/source/**/*.css --output /var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/css-test-output

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: undefined is not a function
    at Function.pleeease.process (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/pleeease/lib/pleeease.js:192:11)
    at DestroyableTransform._transform (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/index.js:32:29)
    at DestroyableTransform.Transform._read (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)

  Error: Command exited with non-zero: 1
  bin/styleguide --styleSource test/projects/shared-css/*.css --title Test Styleguide --overviewPath /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/test_overview.md --appRoot /my-styleguide-book --extraHead <link rel="stylesheet" type="text/css" href="your/custom/style.css"> --extraHead <script src="your/custom/script.js"></script> --commonClass custom-class-1 --commonClass custom-class-2 --styleVariables /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/styles/_styleguide_variables.scss --customColors /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/styles/custom_colors.scss --kssSource /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/css-project/source/**/*.css --output /var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/css-test-output
  events.js:85
        throw er; // Unhandled 'error' event
              ^
  Error: undefined is not a function
      at ChildProcess.<anonymous> (test/integration/npm-package.test.js:192:16)
      at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
  From previous event:
      at Context.<anonymous> (test/integration/npm-package.test.js:66:48)

  4) style guide generated with npm package executable from internal client files "before all" hook:
     Command exited with non-zero: 1
bin/styleguide --styleSource /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/shared-css/*.css --title Test Styleguide --overviewPath /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/test_overview.md --appRoot /my-styleguide-book --extraHead <link rel="stylesheet" type="text/css" href="your/custom/style.css"> --extraHead <script src="your/custom/script.js"></script> --commonClass custom-class-1 --commonClass custom-class-2 --styleVariables /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/styles/_styleguide_variables.scss --customColors /Users/varya/WebDev/SC5/sc5-styleguide/test/projects/scss-project/source/styles/custom_colors.scss --kssSource /var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/lib/app/**/*.scss --output /var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/demo-test-output

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: undefined is not a function
    at Function.pleeease.process (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/pleeease/lib/pleeease.js:192:11)
    at DestroyableTransform._transform (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/index.js:32:29)
    at DestroyableTransform.Transform._read (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/private/var/folders/t0/y3mndsrs3s93jy_bnytjsc4h0000gn/T/sc5-package-smoketest1440415167671/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)

  Error: Command exited with non-zero: 1
  events.js:85
        throw er; // Unhandled 'error' event
              ^
  Error: undefined is not a function
      at ChildProcess.<anonymous> (test/integration/npm-package.test.js:192:16)
      at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
  From previous event:
      at Context.<anonymous> (test/integration/npm-package.test.js:76:38)
```

**Comment by varya** [comment]
This is breaking. Just released 0.3.30 does not work because of it.
