### ISSUE TITLE
Node 4.4 compatibility

### ISSUE THREAD

**Issue by gisu** [SC5/sc5-styleguide#820]
When comes the compatibility for Node 4.x? Got Build failed.

```
npm WARN engine img-stats@0.4.2: wanted: {"node":"~0.10"} (current: {"node":"4.2.0","npm":"2.14.7"})

...

> node-sass@3.3.3 install /Users/gisu/.node/lib/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/gisu/.node/lib/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node

> node-sass@2.0.1 install /Users/gisu/.node/lib/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/pleeease/node_modules/node-sass
> node scripts/install.js

Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/darwin-x64-node-4.2/binding.node

> node-sass@3.3.3 postinstall /Users/gisu/.node/lib/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

` /Users/gisu/.node/lib/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node ` exists.
 testing binary.
Binary is fine; exiting.

> node-sass@2.0.1 postinstall /Users/gisu/.node/lib/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/pleeease/node_modules/node-sass
> node scripts/build.js

module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/gisu/.node/lib/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/pleeease/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
Build failed```

**Comment by willpracht** [comment]
Have you tried bumping to `npm@3`?

**Comment by varya** [comment]
Hi. I checked on node@4.2.0 and npm@2.14.7. It works for me.
Which version of sc5-styleguide you are trying to install? You want it to be global, right?

**Comment by htuoma** [comment]
I had similar problem and it was fixed by updating pleeease version to newest. I see that the pleeease version has been updated after this so this issue is probably fixed.
