### ISSUE TITLE
Installation issue node-sass in dependecies

### ISSUE THREAD

**Issue by askaza** [SC5/sc5-styleguide#866]
Hi, using node v.4.2.2 and npm 2.14.7
During installation appears this issue

```javascript
Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.0.1/darwin-x64-node-4.2/binding.node

> node-sass@3.4.2 postinstall /Users/aska/work/fbu/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

` /Users/aska/work/fbu/node_modules/sc5-styleguide/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-46/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.

> node-sass@2.0.1 postinstall /Users/aska/work/fbu/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/pleeease/node_modules/node-sass
> node scripts/build.js

module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/aska/work/fbu/node_modules/sc5-styleguide/node_modules/gulp-pleeease/node_modules/pleeease/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by varya** [comment]
No usage of node-sass any more, we use postcss.
