### ISSUE TITLE
Error: File not found with singular glob: sc5-styleguide/lib/modules/overview.md

### ISSUE THREAD

**Issue by alice1017** [SC5/sc5-styleguide#868]
# Error: File not found with singular glob: sc5-styleguide/lib/modules/overview.md

When I run this command  `styleguide --kssSource sass/layout.scss --styleSource css/layout.css --output styleguides` an Error has occured. I don't know this error mean. please your help!

### environment

node: `v5.3.0`
npm: `3.3.12`

### The directory structure:

```text
.
├── compile.py
├── config.rb
├── css
│   ├── 960.css
│   └── layout.css
├── index.html
├── index.jinja2
├── js
├── overview.md
├── sass
│   ├── _mixins.scss
│   ├── _variables.scss
│   └── layout.scss
└── styleguides

4 directories, 10 files
```

### command result

```text
Generating style guide to output dir: styleguides
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: File not found with singular glob: /Users/Hayato/.nodebrew/node/v5.3.0/lib/node_modules/sc5-styleguide/lib/modules/overview.md
    at Glob.<anonymous> (/Users/Hayato/.nodebrew/node/v5.3.0/lib/node_modules/sc5-styleguide/node_modules/vinyl-fs/node_modules/glob-stream/index.js:39:11)
    at Glob.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Glob.emit (events.js:169:7)
    at Glob._finish (/Users/Hayato/.nodebrew/node/v5.3.0/lib/node_modules/sc5-styleguide/node_modules/glob/glob.js:172:8)
    at done (/Users/Hayato/.nodebrew/node/v5.3.0/lib/node_modules/sc5-styleguide/node_modules/glob/glob.js:159:12)
    at Glob._processSimple2 (/Users/Hayato/.nodebrew/node/v5.3.0/lib/node_modules/sc5-styleguide/node_modules/glob/glob.js:652:12)
    at /Users/Hayato/.nodebrew/node/v5.3.0/lib/node_modules/sc5-styleguide/node_modules/glob/glob.js:640:10
    at Glob._stat2 (/Users/Hayato/.nodebrew/node/v5.3.0/lib/node_modules/sc5-styleguide/node_modules/glob/glob.js:736:12)
    at lstatcb_ (/Users/Hayato/.nodebrew/node/v5.3.0/lib/node_modules/sc5-styleguide/node_modules/glob/glob.js:728:12)
```

**Comment by bechtold** [comment]
It is looking for an overview.md.
Try adding it to the root directory.

**Comment by alice1017** [comment]
When I set `--overviewPath` option, This error not occured.

**Comment by tomByrer** [comment]
> When I set --overviewPath option, This error not occurred.

I can repeat this error.  Remove the `overviewPath: 'README.md'` from the gulpfile, & it will error out the same, even though `sc5-styleguide/lib/modules/overview.md` exists.
