### ISSUE TITLE
can't run styleguide from command line

### ISSUE THREAD

**Issue by roderickmorales** [SC5/sc5-styleguide#872]
Hello,
I've downloaded the app and is under my /usr/local/lib/node_modules directory.

When I run <code>styleguide --kss-source "testguide/sass/*.scss" --style-source "testguide/style/*.css" --output styleguide --watch --server</code>

I get the following error:
Generating style guide to output dir: styleguide
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: File not found with singular glob: /usr/local/lib/node_modules/sc5-styleguide/lib/modules/overview.md
    at Glob.<anonymous> (/usr/local/lib/node_modules/sc5-styleguide/node_modules/vinyl-fs/node_modules/glob-stream/index.js:39:11)
    at Glob.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Glob.emit (events.js:169:7)
    at Glob._finish (/usr/local/lib/node_modules/sc5-styleguide/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:172:8)
    at done (/usr/local/lib/node_modules/sc5-styleguide/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:159:12)
    at Glob._processSimple2 (/usr/local/lib/node_modules/sc5-styleguide/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:652:12)
    at /usr/local/lib/node_modules/sc5-styleguide/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:640:10
    at Glob._stat2 (/usr/local/lib/node_modules/sc5-styleguide/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:736:12)
    at lstatcb_ (/usr/local/lib/node_modules/sc5-styleguide/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:728:12)

When I look at my directories it adds a styleguide directory at the same level where I'm calling the app from.. which is what I expect (I think?) but the error happens and I've been stuck here for about 6 hours and I'm out of ideas.

Any help would be appreciated.

Best,
-r

**Comment by VictorTolbert** [comment]
Same here. I guess I'll just try the gulp solution.

**Comment by wellersam** [comment]
@VictorTolbert, @roderickmorales 
```
touch overview.md
--overviewPath "overview.md"
```
https://github.com/SC5/sc5-styleguide/issues/868

**Comment by sighonara** [comment]
Thank you @wellersam. Touching the missing file did it for me.

**Comment by roderickmorales** [comment]
@wellersam I forgot to reply since this project went on the back burner for me but thank you! Your suggestion got it working for me and picking it up again now.
