### ISSUE TITLE
Setting custom colours with existing sass variables

### ISSUE THREAD

**Issue by shainanigans** [SC5/sc5-styleguide#987]
Hi there,
Is it possible to set custom colours using my project's sass variables file? It would be great if I could keep my sass variables the single point of truth for any colours I use.

**Comment by junaidrsd** [comment]
Custom colors file should be Postcss file but as postcss can parse sass like syntax so you can import the variables file in custom colors file and can use your color's variables.

**Comment by shainanigans** [comment]
Thanks, @junaidrsd.

I'm having trouble implementing this. This is simplified look at my override file (which, apart from importing the variables, works). $brandPrimary, etc., are variables defined in my variables.scss file. How should the import be written?
```
/*! styleguide overrides */

@import "../../../../../src/assets/scss/helpers/_variables.scss";

/* Main color definitions */
$primary-color: $brandPrimary;
$secondary-color: $brandSecondary;
$tertiary-color: $brandTertiary;

/* Custom Styles */
@define-mixin styleguide_custom_styles {

}
```

I initially had the import path relative to where my override file sits (`@import "../helpers/variables";`), but gulp threw errors so I fixed the path so that it's looking in the right place. However, I get this error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
 TypeError: Cannot read property 'replace' of undefined
  at getVariableTransformedString (D:\projectname\node_modules\postcss-advanced-variables\index.js:47:16)

  at eachAtIfRule (D:\projectname\node_modules\postcss-advanced-variables\index.js:192:18)
  at eachAtRule (D:\projectname\node_modules\postcss-advanced-variables\index.js:103:40)
  at each (D:\projectname\node_modules\postcss-advanced-variables\index.js:65:45)
  at each (D:\projectname\node_modules\postcss-advanced-variables\index.js:67:20)
  at D:\projectname\node_modules\postcss-advanced-variables\index.js:246:3
  at LazyResult.run (D:\projectname\node_modules\postcss\lib\lazy-result.js:286:20)
  at D:\projectname\node_modules\postcss\lib\lazy-result.js:200:37
  at LazyResult.asyncTick (D:\projectname\node_modules\postcss\lib\lazy-result.js:214:15)
  at D:\projectname\node_modules\postcss\lib\lazy-result.js:212:27
  at LazyResult.asyncTick (D:\projectname\node_modules\postcss\lib\lazy-result.js:214:15)
  at D:\projectname\node_modules\postcss\lib\lazy-result.js:205:31
  at process._tickCallback (node.js:364:9)
```

**Comment by junaidrsd** [comment]
@shainanigans the import is ok and I tried your file and it is working fine nothing is wrong in there. Try to remove node modules and re install them that might help.

**Comment by shainanigans** [comment]
@junaidrsd, that did it, thanks!

**Comment by shainanigans** [comment]
Hi @junaidrsd ,
Seems I was a bit premature on closing this. It worked on a simplified variables.scss file, but not on my actual file.

What I discovered is that when I removed all the comments from variables.scss that used the `// this is a comment` style, it worked. For some reason, that style comment throws an error with the postcss processing. All comments must be in the `/* this is a comment */` style.

According to [this stackoverflow post](http://stackoverflow.com/questions/37073474/gulp-postcss-with-precss-plugin-throws-an-error-when-importing-scss-files), declaring the file extension on the import should allow me to use the `// this is a comment` style of commenting, but it doesn't. Any ideas?

**Comment by junaidrsd** [comment]
Hello @shainanigans,
Custom colors are using postcss and postcss syntax is more like vanilla css. Unfortunately vanilla css does not allow single-line comments `// this is a comment` but multiline comments like you said `/* this is a comment */`. So you need to convert single line comments to multiline from every importing sass files.

**Comment by shainanigans** [comment]
Thanks, @junaidrsd. That makes sense but it would be great if there were a work around like integrating [something like this](https://github.com/postcss/postcss-scss). Any chance of seeing something like that in a future release?
